#!/usr/bin/env bash
# Publish the back catalogue to TikTok, ONE video per run, from a queue file. Called by launchd every
# couple of hours (see install_backfill.sh), or by hand to test.
#
# Why a queue and not a loop: the account had eleven videos on Instagram and, until Upload-Post, none
# public on TikTok (the native app was never audited, so every post went out SELF_ONLY). Dropping
# them all at once reads as spam to the platform and to a viewer; one every two hours reads as a
# channel. launchd runs a missed slot when the Mac wakes, a shell loop dies with the lid.
#
# Each video is REBUILT before it goes out — metadata (the curated hashtag bank), captions (the
# readable Italian subtitles) and assemble (watermark on every spoken frame) — so the TikTok copy
# carries everything the channel has learned since the Instagram copy went up. Voice and images are
# reused as they are; nothing is regenerated by a model except the subtitles and the caption.
#
# Queue: projects/_auto/tiktok_backfill.txt, one project slug per line, # comments allowed. The
# first line is popped BEFORE the work starts, so a crash cannot repost the same video every two
# hours; a failed publish is re-queued at the end once, then dropped with a note in the done-file.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:${PATH:-}"
export PYTHONPATH="$ROOT/src"
cd "$ROOT"
AUTO="$ROOT/projects/_auto"
QUEUE="$AUTO/tiktok_backfill.txt"
DONE="$AUTO/tiktok_backfill_done.txt"
LOCK="$AUTO/backfill.lock"
mkdir -p "$AUTO"
exec >>"$AUTO/backfill.log" 2>&1
echo "=== $(date '+%F %T') backfill run ==="

[ -f "$QUEUE" ] || { echo "no queue file ($QUEUE) — nothing to do"; exit 0; }
if ! mkdir "$LOCK" 2>/dev/null; then echo "another backfill is running ($LOCK) — skipping this slot"; exit 0; fi
trap 'rmdir "$LOCK" 2>/dev/null' EXIT

PY="$ROOT/.venv/bin/python"
SLUG="$("$PY" - "$QUEUE" <<'PY'
import sys, pathlib
p = pathlib.Path(sys.argv[1]); lines = p.read_text().splitlines()
for i, line in enumerate(lines):
    s = line.strip()
    if s and not s.startswith("#"):
        del lines[i]; p.write_text("\n".join(lines) + ("\n" if lines else "")); print(s); break
PY
)"
[ -n "$SLUG" ] || { echo "queue empty — nothing to do"; exit 0; }
[ -d "$ROOT/projects/$SLUG" ] || { echo "$(date '+%T') $SLUG: no such project — dropped" | tee -a "$DONE"; exit 0; }
echo "video: $SLUG"

CAF=""; command -v caffeinate >/dev/null 2>&1 && CAF="caffeinate -i -m -s"
AVP="$ROOT/.venv/bin/avp"
step() { echo "--- $1 $(date '+%T')"; $CAF "$AVP" "$1" "$SLUG" --config "$ROOT/config.yaml" "${@:2}"; }

fail() {
  echo "$(date '+%T') $SLUG: FAILED at $1"
  if grep -q "^.* $SLUG: FAILED" "$DONE" 2>/dev/null; then
    echo "$(date '+%T') $SLUG: FAILED at $1 — second failure, dropped" >>"$DONE"
  else
    echo "$(date '+%T') $SLUG: FAILED at $1 — re-queued once" >>"$DONE"
    echo "$SLUG" >>"$QUEUE"
  fi
  exit 1
}

# The catalogue predates the wonder voice ("The Gutted Moon of Saturn"): rewrite the narration through
# fact sheet → polish → fact-check first, images untouched; the voice then re-synthesises only the
# lines that changed. Set BACKFILL_KEEP_VOICE=1 to republish the original narration instead.
if [ "${BACKFILL_KEEP_VOICE:-0}" != "1" ]; then
  echo "--- repolish $(date '+%T')"; $CAF "$PY" "$ROOT/tools/repolish.py" "$SLUG" || fail repolish
  step voice || fail voice
fi
step metadata || fail metadata          # captions + hashtags from the curated bank
step captions || fail captions          # readable Italian subtitles (adapted, budgeted)
step assemble || fail assemble          # watermark through the spoken bridge, new cards
MP4="$ROOT/projects/$SLUG/$SLUG.mp4"
DUR="$(ffprobe -v 0 -show_entries format=duration -of csv=p=0 "$MP4" 2>/dev/null || echo 0)"
"$PY" -c "import sys; d=float('${DUR:-0}' or 0); sys.exit(0 if 5 < d < 60 else 1)" || fail "duration ${DUR}s"
echo "duration: ${DUR}s"
echo "--- publish $(date '+%T')"
OUT="$($CAF "$AVP" publish "$SLUG" --go --platforms tiktok --config "$ROOT/config.yaml" 2>&1)"
echo "$OUT"
echo "$OUT" | grep -q "Published to tiktok" || fail publish
echo "$(date '+%T') $SLUG: published to tiktok" >>"$DONE"
echo "OK $(date '+%T')"
